### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by CakesTwix** [andrwgldmn/SEcontexts_parser#8]
File "SEcontexts_parser.py", line 27
    os.system('rm allows.te && mv temp.te allows.te')
                                                    ^
IndentationError: unindent does not match any outer indentation level

Python 3.8.3
Manjaro Linux

**Comment by andrwgldmn** [comment]
3.8.* не поддерживается, проверялось на 3.7.* и 2.7.*
